export const APP_LIMITS = {
  MAX_FILE_UPLOAD_SIZE_BYTES: 10 * 1024 * 1024,
  MAX_BRAND_ASSET_UPLOAD_SIZE_BYTES: 5 * 1024 * 1024,
  MAX_QUEUE_DEPTH_PER_USER: 3,
  GENERATION_RATE_LIMIT_PER_MINUTE: 30,
  SESSION_EXPIRY_DAYS: 7,
  EXPORT_RETENTION_DAYS: 7,
  CACHE_TTL_SECONDS: {
    SHORT: 60,
    MEDIUM: 60 * 10,
    LONG: 60 * 60,
  },
  generationRatePerMinute: 30,
  maxQueueDepthPerUser: 3,
} as const;

