import { fail, ok } from "@/lib/api/response";
import { prisma } from "@/lib/db/prisma";

export const runtime = "nodejs";

/** Public collection cards for marketplace carousel. */
export async function GET() {
  try {
    const rows = await prisma.templateCollection.findMany({
      where: { isPublic: true },
      orderBy: { updatedAt: "desc" },
      take: 24,
    });

    const items = rows.map((c) => {
      const ids = Array.isArray(c.templateIds) ? (c.templateIds as string[]) : [];
      return {
        id: c.id,
        name: c.name,
        description: c.description,
        coverImageUrl: c.coverImageUrl,
        templateCount: ids.length,
        isAutoGenerated: c.isAutoGenerated,
      };
    });

    return ok({ collections: items }, 200);
  } catch (e) {
    console.error(e);
    return fail("INTERNAL_ERROR", "Failed", 500);
  }
}
