import { NextRequest } from "next/server";
import { prisma } from "@/lib/db/prisma";
import { fail, ok } from "@/lib/api/response";

export const runtime = "nodejs";

const TRENDING_KEY = "trending_week";
const NEW_MONTH_KEY = "new_month";

/**
 * Nightly: refresh auto-generated Trending / New collections.
 */
export async function POST(req: NextRequest) {
  const secret = req.headers.get("x-cron-secret") ?? req.headers.get("authorization")?.replace("Bearer ", "");
  if (!secret || secret !== process.env.CRON_SECRET) {
    return fail("UNAUTHORIZED", "Invalid cron secret", 401);
  }

  const admin = await prisma.user.findFirst({ where: { isAdmin: true }, select: { id: true } });
  if (!admin) return fail("INTERNAL_ERROR", "No admin user", 500);

  const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
  let trendingIds: string[] = [];
  try {
    const hot = await prisma.$queryRaw<{ templateId: string; c: bigint }[]>`
      SELECT ti."templateId", COUNT(*)::bigint as c
      FROM "TemplateInstallation" ti
      INNER JOIN "Template" t ON t.id = ti."templateId"
      WHERE ti."installedAt" >= ${sevenDaysAgo}
        AND t."submissionStatus" = 'approved'
        AND t."isActive" = true
        AND t."marketplaceQualityFlagged" = false
      GROUP BY ti."templateId"
      ORDER BY c DESC
      LIMIT 12
    `;
    trendingIds = hot.map((r) => r.templateId);
  } catch {
    trendingIds = [];
  }
  if (trendingIds.length === 0) {
    const fallback = await prisma.template.findMany({
      where: { submissionStatus: "approved", isActive: true, marketplaceQualityFlagged: false },
      orderBy: { installCount: "desc" },
      take: 12,
      select: { id: true },
    });
    trendingIds = fallback.map((t) => t.id);
  }
  const approvedTrending = await prisma.template.findMany({
    where: { id: { in: trendingIds }, submissionStatus: "approved", isActive: true },
    select: { id: true },
  });
  const trendingOrder = trendingIds.filter((tid) => approvedTrending.some((a) => a.id === tid));
  await upsertAutoCollection(
    admin.id,
    TRENDING_KEY,
    "Trending this week",
    "Templates with the most new installs in the last 7 days.",
    trendingOrder
  );

  const newest = await prisma.template.findMany({
    where: { submissionStatus: "approved", isActive: true, marketplaceQualityFlagged: false },
    orderBy: { createdAt: "desc" },
    take: 12,
    select: { id: true },
  });
  await upsertAutoCollection(admin.id, NEW_MONTH_KEY, "New this month", "Recently approved templates.", newest.map((t) => t.id));

  return ok({ ok: true }, 200);
}

async function upsertAutoCollection(
  adminId: string,
  key: string,
  name: string,
  description: string,
  templateIds: string[]
) {
  const existing = await prisma.templateCollection.findFirst({ where: { autoKey: key } });
  if (existing) {
    await prisma.templateCollection.update({
      where: { id: existing.id },
      data: { templateIds: templateIds as any, name, description, isAutoGenerated: true, isPublic: true },
    });
  } else {
    await prisma.templateCollection.create({
      data: {
        name,
        description,
        templateIds: templateIds as any,
        coverImageUrl: null,
        isPublic: true,
        isAutoGenerated: true,
        autoKey: key,
        createdByUserId: adminId,
      },
    });
  }
}
